In [ ]:
# Beta for TSLA

From: https://www.learnpythonwithrune.org/calculate-the-capm-with-python-in-3-easy-steps/

In [1]:
import pandas_datareader as pdr
import datetime as dt
import pandas as pd
import numpy as np
 
tickers = ['AAPL', 'TSLA', '^GSPC']
start = dt.datetime(2017, 2, 1)
end = dt.datetime(2022, 1, 1)
 
data = pdr.get_data_yahoo(tickers, start, end, interval="m")
 
data = data['Adj Close']
 
log_returns = np.log(data/data.shift())

In [2]:
data

Symbols           AAPL         TSLA        ^GSPC
Date
2017-02-01   32.236553    49.998001  2363.639893
2017-03-01   33.952709    55.660000  2362.719971
2017-04-01   33.950340    62.813999  2384.199951
2017-05-01   36.103409    68.202003  2411.800049
2017-06-01   34.178291    72.321999  2423.409912
2017-07-01   35.296036    64.694000  2470.300049
2017-08-01   38.919861    71.180000  2471.649902
2017-09-01   36.718811    68.220001  2519.360107
2017-10-01   40.273468    66.306000  2575.260010
2017-11-01   40.942936    61.770000  2647.580078
2017-12-01   40.463676    62.270000  2673.610107
2018-01-01   40.033287    70.862000  2823.810059
2018-02-01   42.589314    68.612000  2713.830078
2018-03-01   40.280537    53.226002  2640.870117
2018-04-01   39.675541    58.779999  2648.050049
2018-05-01   44.863659    56.945999  2705.270020
2018-06-01   44.612484    68.589996  2718.370117
2018-07-01   45.860893    59.627998  2816.290039
2018-08-01   54.860031    60.332001  2901.520020
2018-09-01   54.595333    52.953999  2913.979980
2018-10-01   52.931400    67.463997  2711.739990
2018-11-01   43.189663    70.096001  2760.169922
2018-12-01   38.282604    66.559998  2506.850098
2019-01-01   40.394043    61.403999  2704.100098
2019-02-01   42.022526    63.976002  2784.489990
2019-03-01   46.297504    55.972000  2834.399902
2019-04-01   48.910351    47.737999  2945.830078
2019-05-01   42.670734    37.032001  2752.060059
2019-06-01   48.425854    44.692001  2941.760010
2019-07-01   52.125313    48.321999  2980.379883
2019-08-01   51.073212    45.122002  2926.459961
2019-09-01   55.007805    48.174000  2976.739990
2019-10-01   61.096321    62.984001  3037.560059
2019-11-01   65.637527    65.987999  3140.979980
2019-12-01   72.337990    83.666000  3230.780029
2020-01-01   76.244972   130.113998  3225.520020
2020-02-01   67.339729   133.598007  2954.219971
2020-03-01   62.790680   104.800003  2584.590088
2020-04-01   72.546692   156.376007  2912.429932
2020-05-01   78.507492   167.000000  3044.310059
2020-06-01   90.322250   215.962006  3100.290039
2020-07-01  105.237312   286.152008  3271.120117
2020-08-01  127.798065   498.320007  3500.310059
2020-09-01  114.902199   429.010010  3363.000000
2020-10-01  108.006683   388.040009  3269.959961
2020-11-01  118.116798   567.599976  3621.629883
2020-12-01  131.877014   705.669983  3756.070068
2021-01-01  131.151489   793.530029  3714.239990
2021-02-01  120.517044   675.500000  3811.149902
2021-03-01  121.582993   667.929993  3972.889893
2021-04-01  130.849792   709.440002  4181.169922
2021-05-01  124.031578   625.219971  4204.109863
2021-06-01  136.555817   679.700012  4297.500000
2021-07-01  145.429535   687.200012  4395.259766
2021-08-01  151.381927   735.719971  4522.680176
2021-09-01  141.293793   775.479980  4307.540039
2021-10-01  149.581696  1114.000000  4605.379883
2021-11-01  165.059113  1144.760010  4567.000000
2021-12-01  177.570007  1056.780029  4766.180176
2022-01-01  173.070007  1049.609985  4662.850098

In [3]:
log_returns

Symbols         AAPL      TSLA     ^GSPC
Date
2017-02-01       NaN       NaN       NaN
2017-03-01  0.051868  0.107279 -0.000389
2017-04-01 -0.000070  0.120916  0.009050
2017-05-01  0.061488  0.082296  0.011510
2017-06-01 -0.054797  0.058654  0.004802
2017-07-01  0.032180 -0.111460  0.019164
2017-08-01  0.097734  0.095543  0.000546
2017-09-01 -0.058215 -0.042474  0.019119
2017-10-01  0.092404 -0.028457  0.021946
2017-11-01  0.016486 -0.070863  0.027696
2017-12-01 -0.011775  0.008062  0.009784
2018-01-01 -0.010693  0.129255  0.054657
2018-02-01  0.061892 -0.032267 -0.039726
2018-03-01 -0.055735 -0.253920 -0.027252
2018-04-01 -0.015133  0.099255  0.002715
2018-05-01  0.122893 -0.031698  0.021378
2018-06-01 -0.005614  0.186043  0.004831
2018-07-01  0.027599 -0.140021  0.035388
2018-08-01  0.179172  0.011737  0.029814
2018-09-01 -0.004837 -0.130439  0.004285
2018-10-01 -0.030952  0.242170 -0.071929
2018-11-01 -0.203396  0.038272  0.017702
2018-12-01 -0.120606 -0.051762 -0.096265
2019-01-01  0.053687 -0.080629  0.075742
2019-02-01  0.039523  0.041033  0.029296
2019-03-01  0.096882 -0.133656  0.017766
2019-04-01  0.054901 -0.159124  0.038560
2019-05-01 -0.136476 -0.253945 -0.068041
2019-06-01  0.126521  0.188012  0.066658
2019-07-01  0.073617  0.078092  0.013043
2019-08-01 -0.020391 -0.068517 -0.018257
2019-09-01  0.074215  0.065449  0.017035
2019-10-01  0.104977  0.268061  0.020226
2019-11-01  0.071696  0.046592  0.033480
2019-12-01  0.097202  0.237360  0.028189
2020-01-01  0.052602  0.441578 -0.001629
2020-02-01 -0.124201  0.026424 -0.087860
2020-03-01 -0.069944 -0.242782 -0.133668
2020-04-01  0.144424  0.400210  0.119421
2020-05-01  0.078964  0.065730  0.044287
2020-06-01  0.140190  0.257109  0.018221
2020-07-01  0.152834  0.281421  0.053637
2020-08-01  0.194233  0.554719  0.067719
2020-09-01 -0.106370 -0.149762 -0.040018
2020-10-01 -0.061888 -0.100372 -0.028056
2020-11-01  0.089481  0.380308  0.102146
2020-12-01  0.110196  0.217731  0.036449
2021-01-01 -0.005517  0.117344 -0.011199
2021-02-01 -0.084562 -0.161038  0.025757
2021-03-01  0.008806 -0.011270  0.041563
2021-04-01  0.073453  0.060293  0.051097
2021-05-01 -0.053514 -0.126372  0.005471
2021-06-01  0.096197  0.083548  0.021971
2021-07-01  0.062958  0.010974  0.022493
2021-08-01  0.040114  0.068224  0.028578
2021-09-01 -0.068965  0.052633 -0.048738
2021-10-01  0.057001  0.362230  0.066858
2021-11-01  0.098461  0.027238 -0.008369
2021-12-01  0.073061 -0.079968  0.042689
2022-01-01 -0.025669 -0.006808 -0.021918

In [7]:
cov = log_returns.cov()
var = log_returns['^GSPC'].var()
 
beta = cov.loc['TSLA', '^GSPC']/var

In [8]:
cov

Symbols      AAPL      TSLA     ^GSPC
Symbols
AAPL     0.006989  0.007521  0.002372
TSLA     0.007521  0.030025  0.003548
^GSPC    0.002372  0.003548  0.002030

In [11]:
cov.loc['TSLA', '^GSPC']

0.0035484868847948164

In [9]:
var

0.0020297884174815934

In [10]:
beta

1.7482053076238893